README.md
lib/crawler.js

- Support `extraHeaders` option
- Refactor handlers for options

Extra headers

---

lib/crawler.js
lib/hccrawler.js
lib/helper.js

- Add comment in [JSDoc](http://usejsdoc.org) style

Add jsdoc style comments

---

.circleci/config.yml
README.md
lib/crawler.js
lib/hccrawler.js
lib/helper.js
package.json
test/hccrawler.test.js
yarn.lock

- Automatically dismisses dialog
- Refactor by separating HCCrawler and Crawler classes
- Make preparation of pages parallel
- Enrich unit tests
- Improved README

Handle dialog

---

README.md

Add NPM shield

---

README.md
lib/hccrawler.js
test/hccrawler.test.js

- Add `allowed_domain` options
- Add `crawler.requestedCount` property

Support allowed domains

---

README.md
lib/crawler.js

Add user agent

---

.circleci/config.yml
README.md
examples/emulate-device.js
examples/multiple-queue.js
examples/override-function.js
examples/pause-resume.js
examples/priority-queue.js
examples/session-cache.js
examples/skip-request.js
lib/cache/base.js
lib/cache/index.js
lib/cache/redis.js
lib/cache/session.js
lib/hccrawler.js
lib/helper.js
package.json
test/hccrawler.test.js
test/helper.test.js
yarn.lock

close https://github.com/yujiosaka/headless-chrome-crawler/issues/14 https://github.com/yujiosaka/headless-chrome-crawler/issues/18
- Add BaseCache, SessionCache and RedisCache
- Add stop/resume/clearCache methods

Add pluggable cache

---

README.md
examples/custom-cache.js

- Add docs for RedisCache, SessionCache and BaseCache

Add docs for caches

---

README.md
cache/base.js
cache/redis.js
cache/session.js
examples/custom-cache.js
examples/delay.js
examples/multiple-queue.js
examples/pause-resume.js
examples/redis-cache.js
lib/hccrawler.js
lib/helper.js
package.json
test/hccrawler.test.js
test/helper.test.js

- Elaborate redis cache examples and tests
- Simplify BaseCache interfaces

Elaborate README, tests and examples

---

.eslintrc.js
CHANGELOG.md
README.md
examples/.eslintrc.js
examples/conditional-screenshot.js
lib/crawler.js
lib/hccrawler.js
lib/helper.js
test/hccrawler.test.js

close https://github.com/yujiosaka/headless-chrome-crawler/issues/12
- Automatically collecting and following links up to max depth
- Prefer destructured style for requiring lodash.js

collect links

---

README.md
lib/crawler.js
lib/helper.js
test/helper.test.js

- Exclude javascript, mailto and other invalid URLs for automatically following links

Resolve url

---

cache/base.js
cache/redis.js
cache/session.js
lib/crawler.js
lib/hccrawler.js
lib/helper.js

- Annotations obey [Closure annotations](https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler)

Force more strict closure jsdoc style

---

lib/hccrawler.js

- Fix a bug of opening too many tabs at the same time

Fix a bug of opening too many tabs when error occured

---

lib/hccrawler.js

url is undefined in this._options

Fix "End requesting" message.

---

CHANGELOG.md
README.md
cache/base.js
cache/redis.js
cache/session.js
examples/custom-cache.js
lib/crawler.js
lib/hccrawler.js
lib/helper.js
package.json
test/cache.test.js
test/hccrawler.test.js
test/helper.test.js
yarn.lock

- Support `obeyRobotsTxt` option
- Support `skipDuplicates` option
- Make `cache` option to be required
- Added docs for `exporter` option
- Modify `BaseCache` interface
Fixes: https://github.com/yujiosaka/headless-chrome-crawler/issues/11

Obey robot txt

---

CHANGELOG.md
README.md
cache/base.js
cache/redis.js
cache/session.js
exporter/base.js
test/cache.test.js

- Support `expire` option for `RedisCache`
Fixes: https://github.com/yujiosaka/headless-chrome-crawler/issues/54

Support expire option for redis cache

---

cache/.eslintrc.js
cache/base.js
cache/session.js
lib/async-events.js
lib/crawler.js
lib/hccrawler.js
lib/helper.js

Fix annotation

---

README.md
examples/priority-queue.js
lib/hccrawler.js

- `maxDepth` should be a constructor option considering restarting crawler with redis cache

maxDepth is a constructor option

---

README.md
lib/hccrawler.js
lib/priority-queue.js
package.json
test/hccrawler.test.js
test/priority-queue.test.js
yarn.lock

- Add docs for distributed setup
- Fix a problem that the crawler stops when no task is queued
Fixes: https://github.com/yujiosaka/headless-chrome-crawler/issues/71

Support distributed crawler

---

lib/hccrawler.js

The bug started when updating puppeteer's version at https://github.com/yujiosaka/headless-chrome-crawler/pull/65 .

Fix a bug of not following robots.txt

---

README.md
lib/hccrawler.js
lib/helper.js
test/helper.test.js

- Support `followSitemapXml` option
Fixes: https://github.com/yujiosaka/headless-chrome-crawler/issues/13

follow sitemaps

---

lib/hccrawler.js

- Do not request sitemap multiple times
- Do not refresh cache expiration every time request queued

Elaborate cache

---

package.json

Fixes: https://github.com/yujiosaka/headless-chrome-crawler/issues/82

drop istanbul

---

CHANGELOG.md
README.md
lib/crawler.js
lib/hccrawler.js
test/hccrawler.test.js

- Emit `newpage` event.
Fixes: #93
FYI @sebastienfi

Support newpage event

---

yarn.lock

[Greenkeeper](https://greenkeeper.io) does not update yarn.lock

bump packages

---

.gitignore
commitlint.config.js
package.json
yarn.lock

- Add setting for for [commitlint](https://github.com/marionebl/commitlint)

chore: setup commitlint

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md

- Adapt a code of conduct from [Contributor Covenant Code of Conduct](https://www.contributor-covenant.org/version/1/4/code-of-conduct.html)
- Adapt a contribution guideline from [Good-CONTRIBUTING.md-template.md](https://gist.github.com/PurpleBooth/b24679402957c63ec426).

chore: add contributing and code of conduct

---

ISSUE_TEMPLATE.md

- Add [issue template](https://github.com/blog/2111-issue-and-pull-request-templates)

chore: issue template

---

CHANGELOG.md
README.md
lib/hccrawler.js
lib/helper.js
test/hccrawler.test.js

Fixes: https://github.com/yujiosaka/headless-chrome-crawler/issues/107 https://github.com/yujiosaka/headless-chrome-crawler/issues/108

feat: support deniedDomains option

---

CHANGELOG.md
README.md
lib/hccrawler.js
test/hccrawler.test.js
test/helper.test.js

Fixes: https://github.com/yujiosaka/headless-chrome-crawler/issues/110

feat: support depthPriority option

---

README.md
lib/hccrawler.js
test/hccrawler.test.js
test/helper.test.js

Fixes: https://github.com/yujiosaka/headless-chrome-crawler/issues/110

Revert 112 revert 109 support depth first order

---

lib/hccrawler.js

Fixes: https://github.com/yujiosaka/headless-chrome-crawler/issues/124

Dont push already crawled url

---

cache/session.js
lib/helper.js
test/helper.test.js

Fixes: https://github.com/yujiosaka/headless-chrome-crawler/issues/127

Commit session cache

---

.circleci/config.yml
package.json
yarn.lock

Fixes: https://github.com/yujiosaka/headless-chrome-crawler/issues/132

chore(greenkeeper): automatically update yarn.lock

---

CHANGELOG.md
README.md
lib/crawler.js
test/hccrawler.test.js

Fixes: https://github.com/yujiosaka/headless-chrome-crawler/issues/150
FYI @bobmaerten

Support wait for option

---

package.json

```
yarn install v1.3.2
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
error hawk@7.0.7: The engine "node" is incompatible with this module. Expected version ">=8.9.0".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

Revert "Update request to the latest version 🚀"

---

.gitignore
CONTRIBUTING.md
README.md
lib/async-events.js
lib/crawler.js
lib/hccrawler.js
lib/helper.js
lib/priority-queue.js
lib/puppeteer.d.ts
lib/types/puppeteer.d.ts
package.json
test/async-events.test.js
tsconfig.json
yarn.lock

Fixes https://github.com/yujiosaka/headless-chrome-crawler/issues/170

Use TypeScript for type validation

---

exporter/base.js
exporter/csv.js
exporter/json-line.js
lib/crawler.js
lib/hccrawler.js
lib/helper.js
lib/priority-queue.js
test/hccrawler.test.js

Fixes: https://github.com/yujiosaka/headless-chrome-crawler/issues/171

chore(lodash): import single lodash functions

---

CHANGELOG.md
README.md
lib/hccrawler.js
test/hccrawler.test.js

Fixes: https://github.com/yujiosaka/headless-chrome-crawler/issues/180

feat(hccrawler): support slowMo option for connection

---

API.md
CHANGELOG.md
README.md
examples/conditional-screenshot.js
examples/csv-exporter.js
examples/custom-cache.js
examples/custom-exporter.js
examples/emulate-device.js
examples/multiple-queue.js
examples/override-function.js
examples/pause-resume.js
examples/priority-queue.js
examples/redis-cache.js
lib/hccrawler.js
lib/priority-queue.js
test/hccrawler.test.js

Make `crawler.queue` to return Promise so that rejection can be handled same as other async methods.

Queue to return promise

---

API.md
lib/crawler.js
lib/hccrawler.js

Wanted to grab `1920x1080` screenshots, but no API.
Now there is. Cheers!

Support setViewport option

---

test/hccrawler/index.test.js

close https://github.com/yujiosaka/headless-chrome-crawler/issues/219

test(hccrawler): remove --disable-dev-shm-usage on test

---

lib/crawler.js
test/hccrawler/index.test.js
test/server/index.js

Fixes: https://github.com/yujiosaka/headless-chrome-crawler/issues/59

fix(hccrawler): fix a bug of CSP breaks the crawler

---

API.md
lib/hccrawler.js
test/hccrawler/index.test.js

Fixes: https://github.com/yujiosaka/headless-chrome-crawler/issues/193

Emit requestdisallowed event

---

API.md
lib/crawler.js
lib/hccrawler.js
lib/puppeteer.d.ts
test/hccrawler/index.test.js
test/server/index.js

Fixes: https://github.com/yujiosaka/headless-chrome-crawler/issues/197, https://github.com/yujiosaka/headless-chrome-crawler/issues/204

Support redirect chain

---

API.md
CHANGELOG.md
lib/crawler.js
lib/hccrawler.js
test/hccrawler/index.test.js

Fixes: https://github.com/yujiosaka/headless-chrome-crawler/issues/238
cc: @LennardWesterveld

feat(crawler): support get and set cookies

---

docs/API.md
docs/CHANGELOG.md
lib/hccrawler.js
test/hccrawler/index.test.js

Fixes https://github.com/yujiosaka/headless-chrome-crawler/issues/258
@cameronbraid

Set options and depth to error

---

package.json
test/.eslintrc.js
test/async-events.test.js
test/cache/helper.js
test/cache/redis.test.js
test/cache/session.test.js
test/exporter.test.js
test/hccrawler/index.test.js
test/hccrawler/redis.test.js
test/helper.test.js
test/priority-queue/helper.js
test/priority-queue/redis.test.js
test/priority-queue/session.test.js
yarn.lock

Switch test runner to jest for more comfortable development environment

Adopt jest

---

docs/API.md
docs/CHANGELOG.md
lib/hccrawler.js
test/hccrawler/index.test.js

Fixes: https://github.com/yujiosaka/headless-chrome-crawler/issues/145

feat(hccrawler): allow access to previous urls

---

docs/CHANGELOG.md
lib/hccrawler.js

fix(hccrawler): allow-low-level-access
