yujiosaka/headless-chrome-crawler

README.md, lib/crawler.js, lib/hccrawler.js
- Support [Puppeteer](https://github.com/GoogleChrome/puppeteer)'s `disconnect`, `versions` and `wsEndpoint` methods
=> Support browser methods

README.md, examples/delay.js, examples/priority-queue.js, examples/skip-duplicates.js, lib/crawler.js, lib/hccrawler.js, test/hccrawler.test.js
close https://github.com/yujiosaka/headless-chrome-crawler/issues/10
- Rename `concurrency` to `maxConcurrency` option for consistency
- Add `maxRequest` option
- Add `crawler.onEnd()` function
- Add `crawler.pendingQueueSize` read-only property
=> Add maxRequest option

CHANGELOG.md, package.json
- Support `maxRequest`, `allowedDomains` and `userAgent` option for [crawler.queue([options])](https://github.com/yujiosaka/headless-chrome-crawler#crawlerqueueoptions)
- Support pluggable cache
- Add [crawler.setMaxRequest(maxRequest)](https://github.com/yujiosaka/headless-chrome-crawler#crawlersetmaxrequestmaxrequest), [crawler.pause()](https://github.com/yujiosaka/headless-chrome-crawler#crawlerpause) and [crawler.resume()](https://github.com/yujiosaka/headless-chrome-crawler#crawlerresume) methods
- Add [crawler.pendingQueueSize](https://github.com/yujiosaka/headless-chrome-crawler#crawlerpendingqueuesize) and [crawler.requestedCount](https://github.com/yujiosaka/headless-chrome-crawler#crawlerrequestedcount) read-only properties
=> Update to 1.1.2

cache/index.js, lib/hccrawler.js
- Remove `cache/index.js` since it's not recommended way of requiring
=> Fix require cache

README.md, lib/crawler.js, lib/hccrawler.js, lib/helper.js, test/hccrawler.test.js, test/helper.test.js
- Fix a bug of `maxDepth` option not working.
- Change `crawler.isPaused`, `crawler.queueSize`, `crawler.pendingQueueSize` and `crawler.requestedCount` from read-only properties to methods.
- Emit `requeststarted`, `requestskipped`, `requestfinished`, `requestfailed`, `maxdepthreached`, `maxrequestreached` and `disconnected` events.
- Trace public APIs and events.
Fixes: https://github.com/yujiosaka/headless-chrome-crawler/issues/27
=> Better debug logs

CHANGELOG.md, package.json
- Support [CSV](https://tools.ietf.org/html/rfc4180) and [JSON Lines](http://jsonlines.org) formats for exporting results
- Emit `requeststarted`, `requestskipped`, `requestfinished`, `requestfailed`, `maxdepthreached`, `maxrequestreached` and `disconnected` events.
- Improve debug logs by tracing public APIs and events.
- Allow `onSuccess` and `evaluatePage` options as `null`.
- Change `crawler.isPaused`, `crawler.queueSize`, `crawler.pendingQueueSize` and `crawler.requestedCount` from read-only properties to methods.
- Fix a bug of ignoring maxDepth option.
=> Release 1.2.4

.eslintrc.js, .gitignore, README.md, cache/base.js, cache/redis.js, cache/session.js, examples/custom-cache.js, examples/custom-exporter.js, examples/emulate-device.js, examples/override-function.js, examples/pause-resume.js, examples/priority-queue.js, lib/async-events.js, lib/hccrawler.js, lib/helper.js, lib/priority-queue.js, package.json, test/async-events.test.js, test/cache.test.js, test/hccrawler.test.js, test/helper.test.js, test/priority-queue.test.js, yarn.lock
- `preRequest`, `onSuccess` and `onError` cannot be overridden from now on
- `requestfailed` event is now fired when all retries fails
- `requestretried` event is fired when request retries
Fixes: https://github.com/yujiosaka/headless-chrome-crawler/issues/56
=> Distributed queue

README.md, lib/hccrawler.js, test/hccrawler.test.js
- Reverts yujiosaka/headless-chrome-crawler#67
- Pass `depth` to the arguments of `onSuccess`
- Add `browser.userAgent()` method
- Fix a bug that overriding `skipDuplicates` option was not working
=> Allow maxDepth option to be overridden

lib/hccrawler.js, test/hccrawler.test.js
The response does not list the properties but methods.
The bug started when updating puppeteer's version at #65 .
=> fix response

lib/crawler.js, lib/hccrawler.js, test/hccrawler.test.js
It doesn't affect public API, but it keeps the code clean.
=> Reduce response object in crawler rather than hccrawler

CHANGELOG.md, package.json
- Emit `newpage` event.
- Support `deniedDomains` and `depthPriority` for [crawler.queue()](https://github.com/yujiosaka/headless-chrome-crawler#crawlerqueueoptions)'s options.
-  Allow `allowedDomains` option to accept a list of regular expressions.
=> chore: bump version to 1.3.3

CHANGELOG.md, README.md, lib/hccrawler.js, test/hccrawler.test.js, test/helper.test.js
Reverts yujiosaka/headless-chrome-crawler#109
It started requesting the same urls many times when depth-first search is enabled:
```
Requested https://www.emin.co.jp/.
Requested https://www.emin.co.jp/blog/news/1506/.
Requested https://www.emin.co.jp/contact/.
Requested https://www.emin.co.jp/blog/lab/.
Requested https://www.emin.co.jp/team/.
Requested https://www.emin.co.jp/careers/.
Requested https://www.emin.co.jp/blog/news/1539/.
Requested https://www.emin.co.jp/blog/.
Requested https://www.emin.co.jp/blog/interview/1098/.
Requested https://www.emin.co.jp/blog/news/1527/.
Requested https://www.emin.co.jp/company/.
Requested https://www.emin.co.jp/contact/.
Requested https://www.emin.co.jp/blog/news/1506/.
Requested https://www.emin.co.jp/blog/lab/.
Requested …
```
=> Revert "feat: support depthPriority option"

CHANGELOG.md, package.json, yarn.lock
- Drop `depthPriority` for [crawler.queue()](https://github.com/yujiosaka/headless-chrome-crawler#crawlerqueueoptions)'s options.
=> chore: bump version to 1.3.4

CHANGELOG.md, README.md, lib/crawler.js, lib/hccrawler.js
Fixed: https://github.com/yujiosaka/headless-chrome-crawler/issues/129
=> Browser cache option

test/hccrawler.test.js
merge this after rebuilding CI 10 times and all the builds succeed.
Fixes: https://github.com/yujiosaka/headless-chrome-crawler/issues/173
=> chore(test): adjust response delay tests' timeouts

.eslintignore
`/coverage` is no longer used after [istanbul dropped](https://github.com/yujiosaka/headless-chrome-crawler/pull/83)
=> chore(eslint): remove .eslintignore

CHANGELOG.md, package.json
- Support `waitFor` for [crawler.queue()](https://github.com/yujiosaka/headless-chrome-crawler#crawlerqueueoptions)'s options.
- Support `slowMo` for [HCCrawler.connect()](#hccrawlerconnectoptions)'s options.
- Fix a bug of not allowed to set `timeout` option per request.
- Fix a bug of crawling twice if one url has a trailing slash on the root folder and the other does not.
=> chore: bump version to 1.5.0

API.md, README.md
A mistake was made when merging https://github.com/yujiosaka/headless-chrome-crawler/pull/206 . Tips should not be in API.md but in README.md
=> chore(doc): move tips from API.md to README.md

API.md, README.md
Seems links went broken in API.md when it's separated from README.md
=> docs(api): fix broken links

package.json, yarn.lock
It was incorrectly installed to dependencies.
It's not used in production of course, so should be moved to devDependencies.
=> chore(package): move husky to devDependencies

CHANGELOG.md, package.json
- Support `cookies` for [crawler.queue()](https://github.com/yujiosaka/headless-chrome-crawler/blob/master/API.md#crawlerqueueoptions)'s options.
- Make `onSuccess` pass `cookies` in the response.
- Update [Puppeteer](https://github.com/GoogleChrome/puppeteer) version to 1.4.0.
=> chore: bump version to 1.7.0

docs/API.md
Failed to add API documents for adding `previousUrl` fields in errors.
https://github.com/yujiosaka/headless-chrome-crawler/pull/270
=> docs(api): add description for previous url in errors

.circleci/config.yml, Dockerfile
Use docker image composed with [this script](https://github.com/yujiosaka/headless-chrome-crawler/blob/master/Dockerfile).
=> test(ci): use docker image for headless chrome crawler

docs/API.md, docs/CHANGELOG.md, examples/conditional-screenshot.js, examples/custom-cache.js, examples/custom-crawl.js, examples/emulate-device.js, examples/multiple-queue.js, examples/override-function.js, examples/pause-resume.js, examples/priority-queue.js, examples/redis-cache.js, lib/crawler.js, lib/hccrawler.js, test/hccrawler/index.test.js
There are growing needs to access Puppeteer's raw `page` object both **before** and **after** requests.
My implementation of `newpage` event was a mistake for the following three reasons:
1. You cannot pass values retrieved from `page` object to the crawling results
2. You cannot access `page` object **after** requests in order get cookie values, console logs and etc.
3. You cannot return `Promise` so that you have to deal with race conditions
Thus, I'd like to introduce new feature of `customCrawl` and hoping to replace `newpage` event by it.
It goes like this:
```js
const HCCrawler = require('headless-chrome-crawler');
(async () => {
const crawler = await HCCrawler.launch({
customCrawl: async (page, crawl) => {
// You can access the page object before requests
await …
```
=> replace newpage by custom crawl

docs/CHANGELOG.md, package.json
- Set `previousUrl` to `onSuccess` argument.
- Set `options`, `depth`, `previousUrl` to errors.
- Support `customCrawl` for [HCCrawler.connect()](https://github.com/yujiosaka/headless-chrome-crawler/blob/master/docs/API.md#hccrawlerconnectoptions) and [HCCrawler.launch()](https://github.com/yujiosaka/headless-chrome-crawler/blob/master/docs/API.md#hccrawlerlaunchoptions)'s options.
- Add [Dockerfile](https://github.com/yujiosaka/headless-chrome-crawler/blob/master/Dockerfile) and [tips](https://github.com/yujiosaka/headless-chrome-crawler/blob/master/docs/TIPS.md) for using [Docker](https://www.docker.com/).
- Drop `newpage` event.
- Update [Puppeteer](https://github.com/GoogleChrome/puppeteer) version to 1.5.0.
- Fix a bug of not marking skipped requests correctly.
- Fix …
=> chore: bump version to 1.8.0
